### PR TITLE
Allow to specify prefix

### PR DESCRIPTION
**Pull request by ayrat555**

### CODE REVIEW

**Comment by mookid** [comment]
why not define a minor map for all the commands (and bind C-c d or whatever to it) rather than hardcoding everything?

**Comment by ayrat555** [comment]
@mookid I added customizable prefix

**Comment by kwrooijen** [comment]
Is it wise to change these bindings? If people are using the old bindings it'll break for them. Not sure if people really mind though. What's your take on this?

**Comment by ayrat555** [comment]
It seems commands are too complex. For every action, a person has to press `C-c C-c`.
But I think I can make `C-c C-c` a default prefix and leave all other key bindings unchanged. so prefix can be customised

**Comment by mookid** [comment]
this change (without changing C-c C-c) allows users to rebind all the commands in one go, seems like a good compromise.

**Comment by ayrat555** [comment]
@mookid should I return `C-c C-c` ?

**Comment by mookid** [comment]
If you go back to C-c C-c, you have a net benefit compared to the current code without breaking user workflows. The discussion for the other change can be in another PR.

**Comment by ayrat555** [comment]
@mookid @kwrooijen I returned the original prefix and opened a pr with simplifications - https://github.com/kwrooijen/cargo.el/pull/111

**Pull request merged**
